services:
  - type: web
    name: dusuncms
    runtime: docker
    plan: free

    dockerfilePath: ./Dockerfile

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: "false"

      - key: LOG_CHANNEL
        value: stack

      - key: FILESYSTEM_DISK
        value: public

      - key: CACHE_STORE
        value: file

      - key: SESSION_DRIVER
        value: file

      - key: QUEUE_CONNECTION
        value: sync